POST http://localhost:5000/cart/656db411b7725c99a7bc5fe5/add
Content-Type: application/json

{
  "productId": "6571daa7a3ce749c9c930a6b",
  "quantity": 1,
  "color" : "red",
  "text" : "Hello",
  "design" : "chrome"
}
