POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "fullName": "Ghada Abdulrhman",
  "email": "ghada.admin@example.com",
  "password": "ghada123",
  "phoneNumber": "+1122113344",
  "city": "Cairo",
  "address": "Masr El Gdyda",
  "isAdmin": true,
  "isDesigner": false
}